### ISSUE TITLE
Workshop 1

### ISSUE THREAD

**Issue by barajap1** [socalrug/2024-Workshop1#1]
Need to decide on 1 workshop, date, and instructor
- Github by Sep?

**Comment by JavOrraca** [comment]
Sep confirmed he can lead git + GitHub workshop

Still remaining:
- [x] Time / duration
- [x] Volunteers / MAC coordination
- [ ] Food, beverages, snacks?
- [ ] Coffee?
- [x] Signup (Eventbrite, Meetup, something else?)
- [ ] Instructions for attendees

**Comment by barajap1** [comment]
I think we should do something like this:
- Time/duration: 4 hours (3 hours instruction and 1 hour questions and trouble-shooting)
- Volunteers / MAC coordination: Pablo can take the lead. (Mostly help with promoting the event)
- Food, beverages, snacks: SoCalR would cover the cost for drinks (coffee, tea, water) and snacks (pastries, granola bars, etc.). We would not offer lunch. 
- Signup: Let's do it through Eventbrite (we can take payment there), we will charge something small so people actually show up ($5?)
- Instructions for attendees: Let's ask Sep if there are any pre-requisites and prep work for before the event that attendees need to complete

**Comment by barajap1** [comment]
Event has been published
I have emails MAC to help advertise the event

**Comment by phdjsep** [comment]
Is `socalrug` an Organization under Github? I'm thinking of having students use Github Codespaces so we avoid all the "it works on my computer" issues, but wanted to know if I should create a free org or can use `socalrug` org if it is one.

**Comment by JavOrraca** [comment]
It's on our to-do list to make it an Organization but I haven't made the
cutover yet since I'll need to copy the secret keys / tokens we have on a
few repos, and I'll need to re-deploy our socalr.org site (I think), and I
think all of our private repos will be deleted. I'll revisit it tomorrow
afternoon and let you know!

**Comment by phdjsep** [comment]
I see. That's too involved. I can always make a free one for this workshop. Lmk

**Comment by JavOrraca** [comment]
@barajap1 and @phdjsep - The SoCal RUG GitHub personal account is now a GitHub Organization. Our Quarto website is temporarily offline but I'll fix this soon.

@phdjsep - Let me know what I can do to help with the GitHub Codespace for this workshop!
